basicapp/urls.py
from django.urls import path
from basicapp import views

# Template tagging
app_name = 'basicapp'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basicapp/', include('basicapp.urls')),
    path('admin/', admin.site.urls),
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world',
                    'number': 100}
    return render(request, 'basicapp/index.html', context=context_dict)

def other(request):
    return render(request, 'basicapp/other.html')

def relative(request):
    return render(request, 'basicapp/relative_url_template.html')

templates/basicapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Smile Studio</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="{% url 'basicapp:other' %}">Other</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        <!-- Anything outside of this will be inherited if you extend -->
        {% endblock body_block %}
    </div>
</body>
</html>

templates/basicapp/index.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
    <h1>Welcome to index!</h1>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
{% endblock body_block %}

templates/basicapp/other.html
<!DOCTYPE html>
{% extends "basicapp/base.html" %}
{% block body_block %}
    <h1>Welcome to other!</h1>
    <h2>This is an example of template inheritance!</h2>
{% endblock body_block %}

templates/basicapp/relative_url_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome to relative url templates</h1>
    <a href="{% url 'basicapp:other' %}">other</a>
    <a href="{% url 'admin:index' %}">Admin</a>
    <a href="{% url 'index' %}">Go to index!</a>
</body>
</html>